image: renaultdigital/gitlab-runner-base

stages:
  - prebuild
  - build

prebuild:base:
  stage: prebuild
  script:
    - docker build -t renaultdigital/gitlab-runner-base gitlab-runner-base

build:elixir:
  stage: build
  script:
    - docker build -t renaultdigital/gitlab-runner-elixir gitlab-runner-elixir

build:node7:
  stage: build
  script:
    - docker build -t renaultdigital/gitlab-runner-node7 gitlab-runner-node7

build:node7-openjdk8:
  stage: build
  script:
    - docker build -t renaultdigital/gitlab-runner-node7-openjdk8 gitlab-runner-node7-openjdk8

build:node8:
  stage: build
  script:
    - docker build -t renaultdigital/gitlab-runner-node8 gitlab-runner-node8

build:node8-openjdk8:
  stage: build
  script:
    - docker build -t renaultdigital/gitlab-runner-node8-openjdk8 gitlab-runner-node8-openjdk8

build:node9:
  stage: build
  script:
    - docker build -t renaultdigital/gitlab-runner-node9 gitlab-runner-node9

build:gitbook:
  stage: build
  script:
    - docker build -t renaultdigital/gitlab-runner-gitbook gitlab-runner-gitbook

build:kube:
  stage: build
  script:
    - docker build -t renaultdigital/gitlab-runner-kube gitlab-runner-kube
